const eventos = [
  {
    id: 1,
    idDestino: 1,
    nombre: "Festival del Viento y el Parapente",
    tipoEvento: "DEPORTIVO",
    fechaInicio: "2026-03-15",
    fechaFin: "2026-03-19",
    descripcion: "Festival que reúne a los mejores pilotos de parapente nacionales e internacionales aprovechando los vientos de la zona.",
  },
  {
    id: 5,
    idDestino: 2,
    nombre: "Festival de Cine de Santa Fe de Antioquia",
    tipoEvento: "CULTURAL",
    fechaInicio: "2026-12-04",
    fechaFin: "2026-12-08",
    descripcion: "El festival de cine independiente más antiguo de la región, con proyecciones al aire libre en plazas coloniales.",
  },
  {
    id: 6,
    idDestino: 3,
    nombre: "Festival Nacional del Viento y las Cometas",
    tipoEvento: "RECREATIVO",
    fechaInicio: "2026-08-15",
    fechaFin: "2026-08-17",
    descripcion: "Cientos de cometas de todas las formas y colores llenan el cielo de la gran plaza principal aprovechando los vientos de agosto.",
  },
  {
    id: 7,
    idDestino: 5,
    nombre: "Mompox Jazz Festival",
    tipoEvento: "CULTURAL",
    fechaInicio: "2026-10-15",
    fechaFin: "2026-10-18",
    descripcion: "Encuentro musical de talla mundial a orillas del río Magdalena, fusionando jazz tradicional con ritmos caribeños.",
  },
  {
    id: 8,
    idDestino: 6,
    nombre: "Hay Festival Jericó",
    tipoEvento: "CULTURAL",
    fechaInicio: "2026-01-23",
    fechaFin: "2026-01-25",
    descripcion: "Celebración cultural que reúne literatura, música, cine y artes con intelectuales nacionales e internacionales.",
  },
  {
    id: 9,
    idDestino: 4,
    nombre: "Festiver (Festival de Cine Verde)",
    tipoEvento: "AMBIENTAL",
    fechaInicio: "2026-09-17",
    fechaFin: "2026-09-20",
    descripcion: "Festival dedicado al cine verde y ambiental, buscando concientizar a través de producciones audiovisuales.",
  },
];
export const obtenerEventos = () => eventos;
export const obtenerEventosPorDestino = (idDestino) => eventos.filter((e) => e.idDestino === idDestino);